# Generated by Django 4.2.7 on 2024-03-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_alter_comment_parrent_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
