# Generated by Django 4.2.7 on 2024-03-18 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parrent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='myblog.comment'),
        ),
    ]
